modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="momentariycore2"
version="3.0"
displayName="Momentariy Core2"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://perodiumcraft.ucoz.net"
updateJSONURL="https://github.com/Momentariy/MomentariyCore2/blob/master/version.json"
logoFile="logo.png"
authors="Momentariy"
description='''
Core for Momentariy mods on version 1.15.2
'''

[[dependencies.momentariycore2]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"



